# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# To make sure that each time we create the database, it is created with new information
User.destroy_all
Resort.destroy_all

users = User.create([
  {name: "Lindsay Vonn", zip: "90210", ski: true, snowboard: true, email: "lindsay.vonn@gmail.com", level: 4, travel: true, decision_driver: 3, airport: "LAX", password_digest: "abcdefg" },
  {name: "Shawn White", zip: "80123", ski: false, snowboard: true, email: "shawn.white@gmail.com", level: 4, travel: true, decision_driver: 2, airport: "ORD", password_digest: "abcdefg" },
  {name: "Kyle Mack", zip: "10011", ski: false, snowboard: true, email: "kyle.mack@gmail.com", level: 4, travel: true, decision_driver: 1, airport: "JFK", password_digest: "abcdefg" },
  {name: "Bob James", zip: "94107", ski: true, snowboard: false, email: "bob.james@gmail.com", level: 3, travel: false, decision_driver: 2, airport: "SFO", password_digest: "abcdefg" },
  {name: "Warren Miller", zip: "92626", ski: true, snowboard: true, email: "warren.miller@gmail.com", level: 4, travel: true, decision_driver: 2, airport: "SNA", password_digest: "abcdefg" }
  ])

resorts = Resort.create([
  {name: "Deer Valley Resort", address: "2250 Deer Valley Drive South, Park City, UT, 84060", country: "USA", website: "www.deervalleyresort.com", phone_number: "1.800.424.3337", skiable_acres: 2026, lift_count: 24, run_count: 101, major_airport: "SLC", snowboard: false, level_green: 27, level_blue: 41, level_black: 16, level_double_black: 16, sno_country_id: "801004", description: "Deer Valley is consistently ranked #1 in guest service among ski resorts in North America, as rated by the readers of SKI Magazine, and delivers an unmatched experience for your winter vacation. We understand that the finer details make a big difference, which is why Deer Valley offers first-class amenities such as uniformed ski valets, groomed-to-perfection slopes, award-winning cuisine, onsite childcare and convenient lift, lodging and rental packages through our own lodging and reservations division.  We invite you to enjoy The Greatest Snow On Earth® with an annual average of 300 inches blanketing Deer Valley’s six mountains – Little Baldy Peak, Bald Eagle, Bald, Flagstaff, Empire and Lady Morgan – offering a thrilling day for skiers of all abilities." }, 
  {name: "Snowbasin", address: "3925 East Snowbasin Road, Hunstville, UT, 84317", country: "USA", website: "www.snowbasin.com", phone_number: "1.888.437.5488", skiable_acres: 3000, lift_count: 9, run_count: 104, major_airport: "SLC", snowboard: true, level_green: 20, level_blue: 50, level_black: 15, level_double_black: 15, description: "Often overlooked because of the famous resorts in Park City and the Cottonwood Canyons, Snowbasin is a gem of a resort, located 45 minutes from the Salt Lake International Airport and eight miles from Ogden Valley. Snowbasin has diverse terrain ranging from beginner to expert, with three terrain parks, wide-open bowls, trees and glades, groomers and an abundance of light, Utah powder. Downtown Ogden offers a great aprés scene for when it's time to retire from the slopes.", sno_country_id: "801009" },
  {name: "Arapahoe Basin", address: "28194 US Highway 6, Dillon, CO 80435", country: "USA", website: "www.arapahoebasin.com", phone_number: "1.888.272.7246", skiable_acres: 960, lift_count: 8, run_count: 109, major_airport: "DEN", snowboard: true, level_green: 10, level_blue: 30, level_black: 37, level_double_black: 23, sno_country_id: "303001", description: "Arapahoe Basin sits high along Loveland Pass in Summit County, Colorado and home to great steep skiing, long groomers and a friendly vibe that welcomes guests of all ability levels.  Located approximately 60 miles from Denver, the mountain is a great option for skiers traveling from the Front Range.  A-Basin is a great option for all ability types offering up some excellent expert terrain combined with long wide groomers and a learner’s slope for beginners. With 109 trails and eight chairlifts, the ski resort sits at the base of the continental divide and has one of the highest base elevations in Colorado.  Terrain options are plentiful with high-alpine bowls, tree glades, chutes, wide-open groomers and amazing off-piste options." }, 
  {name: "Aspen (AJAX) Resort", address: "601 East Deen Street, Aspen, CO, 81611", country: "USA", website: "www.skiaspen.com", phone_number: "1.800.262.7736", skiable_acres: 673, lift_count: 8, run_count: 76, major_airport: "DEN", local_airport: "ASE", snowboard: true, level_green: 0, level_blue: 48, level_black: 26, level_double_black: 26, sno_country_id: "303003", description: "Anyplace else, this would be considered four separate vacations, but not in Aspen, where skiers will find more than 5,300 acres of terrain between Snowmass, Aspen Mountain (Ajax), Aspen Highlands and Buttermilk. Not to mention the endless dining, nightlife and shopping the town of Aspen is known for, providing more than enough reasons to visit one of the world's most famous and exciting ski resorts. There iss no better time to experience 'The Power of Four'.  Off the mountain, Aspen's dining scene plays on the world's stage, garnering international attention for the caliber of cuisine served in more than 80 downtown restaurants." }, 
  {name: "Alyeska Resort", address: "1000 Arlberg Avenue, Girdwood, AK, 99587", country: "USA", website: "www.alyeskaresort.com", phone_number: "1.800.880.3880", skiable_acres: 1400, lift_count: 9, run_count: 73, major_airport: "ANC", snowboard: true, level_green: 11, level_blue: 52, level_black: 18.5, level_double_black: 18.5, sno_country_id: "907002", description: "Alyeska offers mountain experiences for skiers and riders at all levels.  Tree-lined groomed runs are ideal for the beginner. Intermediate and advanced skiers love the wide open bowls and long top-to-bottom runs.Experts love the North Face, featuring North America’s longest continuous double black run. Freestylers can check out the features at either terrain park." },
  {name: "Mount Baker", address: "1420 Iowa Street, Bellingham, WA, 98229", country: "USA", website: "www.mtbaker.com", phone_number: "1.360.734.6771", skiable_acres: 1000, lift_count: 10, run_count: 31, major_airport: "SEA", snowboard: true, level_green: 24, level_blue: 45, level_black: 15, level_double_black: 16, sno_country_id: "206003", description: "Mt. Baker Ski Area, in Northern Washington, is a powderhound mecca. The ski area averages the most annual snowfall, 641 inches, in the entire world and holds the record for most snowfall in a single season, 1,140 inches in the '98-'99 season. The ski area also annually plays host to the largest snowboard race in the world with 240 competitors in its Legendary Banked Slalom. Guests can benefit from the Baker Bus, transportation provided throughout the Whatcom County to Mt. Baker." },
  {name: "Sun Valley", address: "1 Sun Valley Road, Sun Valley, ID, 83353", country: "USA", website: "www.sunvalley.com", phone_number: "1.800.786.8259", skiable_acres: 2154, lift_count: 18, run_count: 80, major_airport: "SUN", snowboard: true, level_green: 36, level_blue: 42, level_black: 10, level_double_black: 10, sno_country_id: "208012", description: "We’re not saying Sun Valley has special powers, but a lot of magical things do happen here. The slopes on Bald and Dollar mountains enjoy a nearly lift line–free existence all winter long, not to mention a nearly cloud-free one. Plus there’s a 26,000-square-foot family center with everything from lessons to rentals to lockers. Our restaurants have menus loaded with fresh gourmet options from inexpensive to luxury. In summer you can hike, bike, fly-fish or golf in the morning, bowl a few frames in the afternoon, and still catch the sunset from 8,000 feet at the Roundhouse before catching a jazz show. We don’t like to brag, but we do think there’s something out of the ordinary going on in these hills." },  
  {name: "Breckenridge", address: "1599 C Summit County Road Breckenridge, CO, 80424", country: "USA", website: "www.breckenridge.com", phone_number: "1.800.789.7669", skiable_acres: 2908, lift_count: 35, run_count: 187, major_airport: "DEN", snowboard: true, level_green: 11, level_blue: 31, level_black: 24, level_double_black: 34, sno_country_id: "303007", description: "When gold was discovered along the Blue River in the 1800s, miners flocked to Breckenridge to seek their fortune. Today, skiers and snowboarders head to Breckenridge seeking something almost as valuable: the perfect mountain town." }, 
  {name: "Taos Ski Valley", address: "116 Sutton Place, Taos Ski Valley, NM, 87525", country: "USA", website: "www.taosskivalley.com", phone_number: "1.575.776.2291", skiable_acres: 1294, lift_count: 15, run_count: 113, major_airport: "TSM", snowboard: true, level_green: 24, level_blue: 25, level_black: 25, level_double_black: 26, sno_country_id: "505009", description: "Taos Ski Valley is located in the Sangre De Cristo Mountains in Northern New Mexico and is home to a distinctive European atmosphere combined with local Native American and Spanish cultures. Taos is a powder lover’s paradise and is known for having light dry powder, undetectable lift lines, steep chutes, big bumps, cornices and tree glades. The resort grants access to 1,294 acres of skiable terrain and receives an average 300 inches of snowfall annually. The ski area has a great mix of terrain providing trails for all ability types and is home to one of the country’s highest rated ski schools." }, 
  {name: "Kicking Horse Resort", address: "1500 Kicking Horse Trail, Golden, BC V0A 1H0", country: "Canada", website: "www.kickinghorseresort.com", phone_number: "1.866.754.5425", skiable_acres: 2800, lift_count: 8, run_count: 120, major_airport: "YYC", snowboard: true, level_green: 20, level_blue: 20, level_black: 45, level_double_black: 15, sno_country_id: "250002", description: "Kicking Horse Mountain Resort is a great destination for skiers and riders looking for a diverse mix of challenging terrain and excellent snow conditions. Located about 14km outside of Golden, British Columbia, Kicking Horse features one of the longest vertical drops in North America. The ski area is home to large alpine bowls, long steep chutes and short lift lines.  Kicking Horse Mountain Resort is a hidden gem in British Columbia. The snow that falls at Kicking Horse is consistently dry, light and a powder lover’s dream." }
  ])